### ISSUE TITLE
input read

### ISSUE THREAD

**Issue by DavidFord1** [berndporr/pyFirmata2#16]
Hello

If the switch is connected to pin 3
The LED connected to pin 2 should turn on
not work!

import pyfirmata2
import time

board = pyfirmata2.Arduino('COM6')
led_pin = board.get_pin('d:2:o')
button_pin = board.get_pin('d:0:i')

while True:
    if button_pin.read() == 1:
        led_pin.write(1)
    else:
        led_pin.write(0)

**Comment by berndporr** [comment]
1. You haven't read the README. This library is about events/callbacks. It doesn't suppport polling.
2. You haven't explained how "the switch" has been connected. I've noticed it has no pullup enabled.

`digital-in.py` works as expected:
```
./digital-in.py 
Setting up the connection to the board ...
To stop the program press return.
Button released
Button released
Button pressed
Button released
```
In order to prevent people raising issues like this in the future any `read()` to an input will now raise an exception with a message that the user should either use callbacks or pyfirmata1.
