### ISSUE TITLE
Sampling rate

### ISSUE THREAD

**Issue by omersayli** [berndporr/pyFirmata2#5]
Sorry to ask again,

Using serial library in Python and baudrate=250000 and Arduino Due, I almost get 6kHz sampling rate (I even use typical Serial.println() command in Arduino part, no special byte transmission).  I even saw some people having incredible transmission rates using some tricks. Maybe it would be lower for Arduino Uno. 
I  think higher sampling rates could be possible for pyFirmata2, which would be great. 

Thanks

**Comment by berndporr** [comment]
firmata is a standard protocol which has been defined here http://firmata.org/wiki/Main_Page. The firmware has been internally limited to max 100Hz so that even if you transmit all analogue inputs and digital I/O a sampling rate of 100Hz can be guaranteed. Firmata establishes an internal clock which means that within 10ms _all_ conversions can take place. It guarantees this sampling rate.
What you are talking about are people using println as fast as possible but that won't guarantee a stable sampling rate and is dependent on the number of channels. Of course you can do that yourself by writing a small sketch what you have done but that's not the purpose of firmata but rather providing a reliable and configurable protocol.
If you want to increase the sampling rate of firmata I'd recommend to pitch it to the firmata team (https://github.com/firmata), create a patch and convince them that this can be done in a reliable manner and is robust.

**Comment by berndporr** [comment]
While looking for the code bit where there was the 100Hz limit in firmata it's now 1kHz:
https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L43

**Comment by berndporr** [comment]
If you clone it from git  and install it from there you should be able to go up to 1kHz sampling rate but I haven't tested it.

**Comment by omersayli** [comment]
Thanks, 
Used that ino file. I read values in a loop using Pyfirmata read function -without sleep function-. I get 20kHz but values were mostly repetitions (flat values).

**Comment by berndporr** [comment]
Note that this is pyfirmata2 (!) and not pyfirmata. In pyfirmata2 the Arduino firmware establishes the sampling rate and then in python you register a _callback_ when new data has arrived. Read the instructions and see the demos. If you need support with pyfirmata (one) then contact the original author. I urge you to understand that a delay command _cannot_ establish a reliable sampling rate. I'm closing this now and won't provide more support as you clearly haven't read the docs.
