### ISSUE TITLE
Error:Use a callback handler for pin Analog pin 0

### ISSUE THREAD

**Issue by EhsanMasoumi** [berndporr/pyFirmata2#7]
Hi, 

I try to run the code and I get this error "Use a callback handler for pin Analog pin 0". I changed the resolution of the Due port in both board.h and standard Firmata sketch to 12 bit

Would appreciate your help

**Comment by berndporr** [comment]
Which code?

**Comment by berndporr** [comment]
If the error "Use a callback handler ..." is displayed this usually means that you are *not* using callback handlers in your code but trying access the io-pins *directly*. This library won't allow accessing pins directly because it uses callback handlers. See the main README:
```
No loops and "sleep" commands: pyFirmata2 is an updated version of pyFirmata which replaces loops with callbacks. Instead of unreliable and disruptive "sleep" commands in a loop the Python application registers callbacks with pyfirmata2 which are then called every time new data has arrived. This means for the analogue channels the callbacks are called at the specified sampling rate while the digital ports call the callback functions after a state change at the port (from 0 to 1 or 1 to 0).
```
If you don't want to use callback handlers in your code I'd strongly suggest you use the original pyFirmata.

**Comment by berndporr** [comment]
You haven't provided any code so that's just been a guess. For future reference for other people here please post also your code which triggers the error so that I can evaluate if it's a genuine bug with pyFirmata2.
